apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobster-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # initContainer waits for MongoDB to be ready
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for MongoDB..."
              until nc -z mongo-service-jobster2-clusterip 27018; do
                echo "MongoDB not ready, retrying..."
                sleep 2
              done
              echo "MongoDB is up!"
      containers:
        - name: backend
          image: rakshith3/jobsterbackend1
          ports:
            - containerPort: 6000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service-jobster2-clusterip.default.svc.cluster.local:27018/jobster
            - name: JWT_SECRET
              value: "8bc475d7a8a04e6a9bd55a9d6f184e54"
            - name: JWT_LIFETIME
              value: "30d"
---

