apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort           # expose externally
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000           # cluster internal port
      targetPort: 5000     # container port
      nodePort: 30060      # external port to access from other machines
