apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobster-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rakshith3/jobsterbackend1
          ports:
            - containerPort: 6000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service-jobster2:28017/jobster
            - name: JWT_SECRET
              value: "8bc475d7a8a04e6a9bd55a9d6f184e54"
            - name: JWT_LIFETIME
              value: "30d"
---
