apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobster-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rakshith3/jobsterbackend1
          ports:
            - containerPort: 6000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/jobster"
            - name: JWT_SECRET
              value: "YOUR_SECRET"
            - name: JWT_LIFETIME
              value: "30d"
---
