apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobster-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mongo
          image: alpine:3.18          # ✅ fixed: busybox → alpine
          command:
            - sh
            - -c
            - |
              echo "Installing DNS & NC tools..."
              apk add --no-cache bind-tools netcat-openbsd     # ✅ DNS + nc fix
              
              echo "Waiting for MongoDB on 27018..."
              until nc -zv mongo-service-jobster2.default.svc.cluster.local 27018; do
                echo "MongoDB not ready, retrying..."
                sleep 2
              done
              echo "✅ MongoDB is UP!"
      containers:
        - name: backend
          image: rakshith3/jobsterbackend1:latest
          ports:
            - containerPort: 6000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service-jobster2.default.svc.cluster.local:27018/jobster
            - name: JWT_SECRET
              value: "8bc475d7a8a04e6a9bd55a9d6f184e54"
            - name: JWT_LIFETIME
              value: "30d"
