apiVersion: v1
kind: Service
metadata:
  name: jobster-frontend
spec:
  type: NodePort           # expose externally
  selector:
    app: jobster-frontend
  ports:
    - protocol: TCP
      port: 80             # cluster internal port
      targetPort: 80       # container port
      nodePort: 30080      # external port to access from other machines
