apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobster-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobster-frontend
  template:
    metadata:
      labels:
        app: jobster-frontend
    spec:
      containers:
      - name: frontend
        image: rakshith3/jobsterfrontend1
        ports:
        - containerPort: 80
---
