apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobster-ingress
spec:
  rules:
  - host: jobster.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jobster-frontend
            port:
              number: 80
