apiVersion: v1
kind: Service
metadata:
  name: mongo-service-jobster2   # unique service name
spec:
  ports:
    - port: 28017
      targetPort: 28017
  clusterIP: None                 # headless service
  selector:
    app: mongo-jobster2
