apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-jobster2
spec:
  serviceName: "mongo-service-jobster2"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-jobster2
  template:
    metadata:
      labels:
        app: mongo-jobster2
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          command: ["mongod", "--port", "27018", "--bind_ip_all"]   # âœ… REQUIRED FIX
          ports:
            - containerPort: 27018
          volumeMounts:
            - name: mongo-pvc-jobster2
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-pvc-jobster2
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---

