apiVersion: v1
kind: Service
metadata:
  name: mongo-service-jobster2   # unique service name
spec:
  ports:
    - port: 27018
      targetPort: 27018
  clusterIP: None                 # headless service
  selector:
    app: mongo-jobster2
